version: '3.9'

services:
  websocket-server:
    container_name: websocket-server
    restart: unless-stopped
    build: .
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    ports:
      - "3000:3000"
  websocket-ui:
    container_name: websocker-ui
    build: 
      context: ./ui
    volumes:
      - ./ui:/app
      - ./ui/node_modules:/app/node_modules
    ports:
      - '4000:4000'
    restart: unless-stopped