version: '3.9'

services:
  websocket-server:
    container_name: websocket-server
    restart: unless-stopped
    build: .
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    ports:
      - "3000:3000"